# Generated by Django 4.2 on 2023-04-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': '6. Inventory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '3. Products'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': '4. Purchase'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': '5. Sales'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': '2. Units'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': '1. Vendors'},
        ),
    ]
