# Generated by Django 4.2 on 2023-04-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_inventory_pur_qty_alter_inventory_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.FloatField(editable=False),
        ),
    ]
