# Generated by Django 4.2 on 2023-04-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customer_remove_sale_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '7. Customers'},
        ),
    ]
